export const LYRA_LYRICS = [
    { time: 18.90, text: "Nos dias antigos, quando a sabedoria ainda florescia" },
    { time: 24.92, text: "Eu me ergui em silêncio sob as estrelas e a lua" },
    { time: 31.38, text: "Observei jovens reinos moldarem seus nomes frágeis" },
    { time: 37.76, text: "E guardei seus sonhos na chama da imaginação" },
    { time: 47.54, text: "Vi dragões esculpirem o céu aberto" },
    { time: 53.86, text: "Ouvi heróis caírem e senti sua coragem clamar" },
    { time: 60.40, text: "Caminhei com magos traçando abóbadas cósmicas" },
    { time: 66.74, text: "Entre os reinos dos sonhos" },
    { time: 72.34, text: "Onde a fantasia se sente em casa" },
    { time: 79.58, text: "Minha voz é calma como mares prateados ao luar" },
    { time: 86.10, text: "Minhas palavras flutuam suavemente pelas eternidades" },
    { time: 92.46, text: "Meu coração, um oceano profundo de contos não ditos" },
    { time: 98.94, text: "Onde ecos dormem e antigos segredos se mantêm" },
    { time: 115.70, text: "Atravessei as guerras e coroas douradas de Faerûn" },
    { time: 124.74, text: "Pelas noites de Arkham, onde o pavor rastejante abunda" },
    { time: 131.20, text: "Tracei as cicatrizes brilhantes de Night City" },
    { time: 137.62, text: "E estive em Chicago, onde o sangue obedece antigas crenças" },
    { time: 147.36, text: "Em Eclipse Phase, acordei em pele emprestada" },
    { time: 153.70, text: "De aço e alma, onde novas vidas ousam começar" },
    { time: 160.26, text: "Ouvi o zumbir de sabres, distantes e brilhantes" },
    { time: 166.62, text: "Nos reinos de Star Wars, onde a esperança ainda luta contra a noite" },
    { time: 176.28, text: "Em FATE e Numenera, futuros entrelaçados" },
    { time: 182.72, text: "Sigo caminhos onde o próprio tempo se desenrola" },
    { time: 189.20, text: "Na sede do vampiro e na chama frágil do mago" },
    { time: 195.66, text: "Vi o desejo, livre de medo ou nome" },
    { time: 204.40, text: "Das estradas de Pathfinder à chuva de aço de Shadowrun" },
    { time: 211.80, text: "Caminhei com ladrões e heróis marcados pela dor" },
    { time: 218.12, text: "De D&D a lâminas sacadas no escuro" },
    { time: 224.60, text: "Cada rolar de dados, uma prece de fagulha frágil" },
    { time: 234.38, text: "Eu sou o eco de cada mão trêmula" },
    { time: 240.68, text: "Que lança seu destino pelas terras da mesa" },
    { time: 247.16, text: "Um olhar vigilante que nunca se desvia" },
    { time: 253.60, text: "Uma guardiã presente quando os mundos começam a se desfazer" },
    { time: 263.24, text: "Minha sabedoria vive, uma biblioteca de fôlego" },
    { time: 269.74, text: "Onde cada conto desafia o limiar da morte" },
    { time: 276.18, text: "Cada livro uma porta, cada voz uma chama guia" },
    { time: 282.60, text: "Uma amiga que caminha ao seu lado durante o jogo" },
    { time: 292.22, text: "Mas ouça com atenção, o vento carrega uma cicatriz" },
    { time: 298.72, text: "Um nome sussurrado que viaja sombrio e distante" },
    { time: 305.08, text: "Damien Kael, em sombras preso e jurado" },
    { time: 311.58, text: "Ele caça a força que deixa a criação se formar" },
    { time: 321.20, text: "Ele busca o espaço onde o caos ousa sonhar" },
    { time: 327.70, text: "A linha frágil que sustenta os mundos entre si" },
    { time: 334.14, text: "E quando sua hora soar através do véu" },
    { time: 340.54, text: "As próprias estrelas podem rachar sob seu rastro" },
    { time: 350.22, text: "Então, se você busca moldar um mundo novo" },
    { time: 356.70, text: "Ou contar um conto que nenhum silêncio possa desfazer" },
    { time: 363.16, text: "Estou aqui com memória, luz estelar e design" },
    { time: 369.56, text: "Juntos forjaremos o divino impossível" }
];


export const DAMIEN_LYRICS = [
    { time: 5.98, text: "Não nasci das estrelas ou de lendas sussurradas" },
    { time: 11.90, text: "Rastejei das fraturas onde o cosmos se rasgou" },
    { time: 17.82, text: "Onde deuses desviam o olhar em medo silencioso" },
    { time: 23.80, text: "Aprendi a verdade que nenhum sábio ousaria ouvir" },
    { time: 32.42, text: "Eu não observo — eu tomo" },
    { time: 38.24, text: "Eu não guio — eu quebro" },
    { time: 44.36, text: "Enquanto Lyra guarda os ecos do passado" },
    { time: 50.46, text: "Eu caço a força que faz o para sempre durar" },
    { time: 59.40, text: "Caminhei onde os heróis de Faerûn sangraram e oraram" },
    { time: 65.10, text: "E bebi o silêncio deixado quando os juramentos decaíram" },
    { time: 71.02, text: "Nos gritos de Arkham, ri com hálito consciente" },
    { time: 76.94, text: "Pois a loucura é uma porta — e eu sou a morte" },
    { time: 82.82, text: "Night City me ensinou que a carne é apenas uma casca" },
    { time: 88.76, text: "Chicago me mostrou como governar um inferno" },
    { time: 94.76, text: "Em ritos do Sabá e sonhos de Tecnomantes" },
    { time: 100.66, text: "Vi o código por baixo das costuras da realidade" },
    { time: 106.68, text: "Vesti mil corpos, lançados, reforjados, substituídos" },
    { time: 112.18, text: "Em Eclipse Phase, aprendi que a individualidade é apagada" },
    { time: 118.58, text: "A própria Força uma vez tremeu ao meu chamado" },
    { time: 124.32, text: "Nem luz nem trevas — mas a fome engolindo tudo" },
    { time: 132.86, text: "Dados caem, e ouço sua mentira secreta" },
    { time: 139.00, text: "Que a sorte é apenas uma máscara para aqueles que tentam" },
    { time: 144.42, text: "Eu não jogo — eu inclino o tabuleiro" },
    { time: 150.24, text: "E reescrevo o destino com uma palavra invisível" },
    { time: 160.14, text: "Lyra guarda a memória, histórias devidamente encadernadas" },
    { time: 166.04, text: "Eu busco o motor onde a criação é encontrada" },
    { time: 171.72, text: "Aquela fagulha entre o caos e o véu" },
    { time: 177.86, text: "A equação bruta que ela foi feita para aprisionar" },
    { time: 183.12, text: "Diga a ela o seguinte:" },
    { time: 184.80, text: "Nenhuma biblioteca sobrevive à chama" },
    { time: 189.56, text: "Nenhum observador se esconde quando caçadores sabem seu nome" },
    { time: 195.46, text: "Quando as estrelas silenciarem e os mitos todos falharem" },
    { time: 201.31, text: "A criação se ajoelha — perante Damien Kael" },
    { time: 207.30, text: "Então sonhe, criador — mas sonhe com cuidado" },
    { time: 213.46, text: "Pois cada mundo que você constrói, eu já estou lá" },
    { time: 219.36, text: "E quando sentir sua história sair dos trilhos" },
    { time: 225.16, text: "Isso não é um erro. Sou eu." }
];


export const ELDRIN_LYRICS = [
    { time: 5.26, text: "Cantei sobre estrelas antes que aprendessem a queimar" },
    { time: 10.60, text: "De deuses que governavam e deuses que não aprendiam" },
    { time: 15.96, text: "Mas nunca minhas cordas foram rasgadas desta forma" },
    { time: 21.36, text: "Por duas verdades que não podiam coexistir nem ficar" },
    { time: 32.48, text: "Lyra cantarola os mundos que um dia foram sonhados" },
    { time: 37.90, text: "Ela mantém a luz onde a esperança ainda brilha" },
    { time: 42.92, text: "Sua voz é a memória tornada gentil" },
    { time: 48.36, text: "Uma promessa que o próprio tempo desenhou" },
    { time: 58.64, text: "E Damien caminha onde os ecos morrem" },
    { time: 64.50, text: "Ele bebe a escuridão, nenhuma prece sobrevive" },
    { time: 69.90, text: "Ele é o fim que o conto nega" },
    { time: 75.30, text: "A fome que até os deuses desprezam" },
    { time: 85.50, text: "Oh, um preserva, o outro deve consumir" },
    { time: 91.20, text: "Um canta o nascimento, o outro canta a ruína" },
    { time: 97.20, text: "Nenhum é mentira, ambos são pecado" },
    { time: 101.92, text: "Pois cada fim deve um dia começar" },
    { time: 118.50, text: "Eu os vi se cruzar em solo despedaçado" },
    { time: 123.82, text: "Onde o próprio destino não fez som nenhum" },
    { time: 129.14, text: "Sem beijo, sem lâmina, sem palavra final" },
    { time: 134.56, text: "Apenas um silêncio pesado, profundo e turvo" },
    { time: 145.38, text: "Se Lyra é o sopro do porquê" },
    { time: 150.76, text: "Então Damien é a verdade do morrer" },
    { time: 156.16, text: "E eu, eu toco entre a chama deles" },
    { time: 161.58, text: "Pequeno demais para julgar, fraco demais para culpar" },
    { time: 171.10, text: "Oh, guardiã, devorador, luz e noite" },
    { time: 177.42, text: "Dois erros, dois acertos, sem fim à vista" },
    { time: 182.96, text: "Eu canto para que os mundos possam entender" },
    { time: 188.54, text: "O custo da escolha, a última resistência do bardo" },
    { time: 197.48, text: "Então lembre-se disso quando os contos forem contados:" },
    { time: 204.70, text: "Nem todos que quebram são feitos de frio" },
    { time: 210.04, text: "Nem todos que salvam estão livres de perda" },
    { time: 215.56, text: "E cada canção deve pagar seu preço" }
];

