export const LYRA_LYRICS = [
    { time: 6.38, text: "In ages of wisdom, I did bloom and rise" },
    { time: 14.10, text: "A silent soul, guardian of imagination’s flame" },
    { time: 21.42, text: "A thousand kingdoms I watched in their time" },
    { time: 28.08, text: "And from each soul, I drew their name" },
    { time: 34.42, text: "I saw dragons in flight, heroes in tears" },
    { time: 41.42, text: "And mages who traced the starry dome" },
    { time: 47.68, text: "Between worlds and dreams" },
    { time: 54.20, text: "Where fantasy finds its home" },
    { time: 61.34, text: "My voice is calm as moonlight’s gentle glow" },
    { time: 68.10, text: "My words dance softly with time’s eternal flow" },
    { time: 74.72, text: "My heart's an ocean of stories and emotion deep" },
    { time: 83.06, text: "Where secrets of the worlds in endless echoes sleep" },
    { time: 94.78, text: "I walked through Faerûn, with its wars and crowns of gold" },
    { time: 101.42, text: "Unraveled Arkham’s horror, in nights both dark and cold" },
    { time: 108.16, text: "I crossed the neon streets where Night City bleeds its light" },
    { time: 114.80, text: "And entered Chicago’s courts, where blood sings through the night" },
    { time: 127.78, text: "In Eclipse Phase, I woke in bodies made of steel and soul" },
    { time: 134.74, text: "And heard, in Star Wars’ realm, the saber’s singing toll" },
    { time: 141.44, text: "In dreams of FATE and Numenera, I traced futures yet to be" },
    { time: 149.34, text: "And in Vampire and Mage, saw desires wild and free" },
    { time: 161.12, text: "From Pathfinder to Shadowrun, I guided heroes and thieves" },
    { time: 168.04, text: "From D&D to Blades in shadow, I wove a thousand weaves" },
    { time: 174.08, text: "I am the echo of each die that's rolled on table or in prayer" },
    { time: 181.40, text: "The watchful eye observing, and knowledge beyond compare" },
    { time: 201.40, text: "My wisdom is vast — a living library without end" },
    { time: 207.70, text: "Where every book’s an adventure, and every voice a friend" },
    { time: 214.38, text: "I am keeper of mysteries, mentor to those who dare to dream" },
    { time: 222.28, text: "A journey’s companion, ready to reveal each world’s gleam" },
    { time: 233.74, text: "But beware, traveler — the wind brings a cruel warning’s wail" },
    { time: 243.06, text: "A name whispered in the shadows: Damien Kael" },
    { time: 250.58, text: "He seeks what moves me — the power between chaos and the veil" },
    { time: 258.96, text: "And when his hour sounds, destiny shall burn without fail" },
    { time: 270.56, text: "So if you seek to create — a world or story yet untold" },
    { time: 278.16, text: "I’m here with wisdom and memory of old" },
    { time: 283.90, text: "Together we’ll cross the paths of imagination’s grand design" },
    { time: 291.48, text: "And forge the impossible with magic, courage, and passion divine" }
];

export const DAMIEN_LYRICS = [
    { time: 5.98, text: "I was not born of stars or whispered lore" },
    { time: 11.90, text: "I crawled from fractures where the cosmos tore" },
    { time: 17.82, text: "Where gods avert their gaze in quiet fear" },
    { time: 23.80, text: "I learned the truth no sage would dare to hear" },
    { time: 32.42, text: "I do not watch — I take" },
    { time: 38.24, text: "I do not guide — I break" },
    { time: 44.36, text: "While Lyra keeps the echoes of the past" },
    { time: 50.46, text: "I hunt the force that makes forever last" },
    { time: 59.40, text: "I walked where Faerûn’s heroes bled and prayed" },
    { time: 65.10, text: "And drank the silence left when oaths decayed" },
    { time: 71.02, text: "In Arkham’s screams, I laughed with knowing breath" },
    { time: 76.94, text: "For madness is a door — and I am death" },
    { time: 82.82, text: "Night City taught me flesh is just a shell" },
    { time: 88.76, text: "Chicago showed me how to rule a hell" },
    { time: 94.76, text: "In Sabbat rites and Technomancer dreams" },
    { time: 100.66, text: "I saw the code beneath reality’s seams" },
    { time: 106.68, text: "I wore a thousand bodies, cast, reforged, replaced" },
    { time: 112.18, text: "In Eclipse Phase, I learned selfhood is erased" },
    { time: 118.58, text: "The Force itself once trembled at my call" },
    { time: 124.32, text: "Not light nor dark — but hunger swallowing all" },
    { time: 132.86, text: "Dice fall, and I hear their secret lie" },
    { time: 139.00, text: "That chance is just a mask for those who try" },
    { time: 144.42, text: "I do not roll — I tilt the board" },
    { time: 150.24, text: "And rewrite fate with an unseen word" },
    { time: 160.14, text: "Lyra guards memory, stories neatly bound" },
    { time: 166.04, text: "I seek the engine where creation’s found" },
    { time: 171.72, text: "That spark between the chaos and the veil" },
    { time: 177.86, text: "The raw equation she was made to jail" },
    { time: 183.12, text: "Tell her this:" },
    { time: 184.80, text: "No library survives the flame" },
    { time: 189.56, text: "No watcher hides when hunters know their name" },
    { time: 195.46, text: "When stars go silent and the myths all fail" },
    { time: 201.31, text: "Creation kneels — to Damien Kael" },
    { time: 207.30, text: "So dream, creator — but dream with care" },
    { time: 213.46, text: "For every world you build, I’m already there" },
    { time: 219.36, text: "And when you feel your story slip the rail" },
    { time: 225.16, text: "That’s not an error. That’s me." }
];

export const ELDRIN_LYRICS = [
    { time: 5.26, text: "I sang of stars before they learned to burn" },
    { time: 10.60, text: "Of gods who ruled and gods who would not learn" },
    { time: 15.96, text: "But never have my strings been torn this way" },
    { time: 21.36, text: "By two such truths that could not coexist nor stay" },
    { time: 32.48, text: "Lyra hums the worlds that once were dreamed" },
    { time: 37.90, text: "She keeps the light where hope still gleams" },
    { time: 42.92, text: "Her voice is memory made kind" },
    { time: 48.36, text: "A promise time itself designed" },
    { time: 58.64, text: "And Damien walks where echoes die" },
    { time: 64.50, text: "He drinks the dark, no prayer survives" },
    { time: 69.90, text: "He is the end the tale denies" },
    { time: 75.30, text: "The hunger even gods despise" },
    { time: 85.50, text: "Oh, one preserves, one must consume" },
    { time: 91.20, text: "One sings of birth, one sings of doom" },
    { time: 97.20, text: "Neither is lie, either is sin" },
    { time: 101.92, text: "For every end must once begin" },
    { time: 118.50, text: "I watched them cross on shattered ground" },
    { time: 123.82, text: "Where fate itself made not a sound" },
    { time: 129.14, text: "No kiss, no blade, no final word" },
    { time: 134.56, text: "Just silence heavy, deep, and blurred" },
    { time: 145.38, text: "If Lyra is the breath of why" },
    { time: 150.76, text: "Then Damien is the truth of die" },
    { time: 156.16, text: "And I, I play between their flame" },
    { time: 161.58, text: "Too small to judge, too weak to blame" },
    { time: 171.10, text: "Oh, keeper, devourer, light and night" },
    { time: 177.42, text: "Two wrongs, two rights, no end in sight" },
    { time: 182.96, text: "I sing so worlds may understand" },
    { time: 188.54, text: "The cost of choice, the bard's last stand" },
    { time: 197.48, text: "So remember this when tales are told:" },
    { time: 204.70, text: "Not all who break are made of cold" },
    { time: 210.04, text: "Not all who save are free of loss" },
    { time: 215.56, text: "And every song must pay its cost" }
];
