export const LYRA_LYRICS = [
    { time: 18.90, text: "In ancient days when wisdom still would bloom" },
    { time: 24.92, text: "I rose in silence beneath the stars and moon" },
    { time: 31.38, text: "I watched young kingdoms shape their fragile name" },
    { time: 37.76, text: "And held their dreams in imagination's flame" },
    { time: 47.54, text: "I saw the dragons carve the open sky" },
    { time: 53.86, text: "Heard heroes break and felt their courage cry" },
    { time: 60.40, text: "I walked with mages tracing cosmic domes" },
    { time: 66.74, text: "Between the realms of dreams" },
    { time: 72.34, text: "Where fantasy feels home" },
    { time: 79.58, text: "My voice is calm as silver moonlit seas" },
    { time: 86.10, text: "My words drift softly through eternities" },
    { time: 92.46, text: "My heart an ocean deep with tales untold" },
    { time: 98.94, text: "Where echoes sleep and ancient secrets hold" },
    { time: 115.70, text: "I crossed through Faerûn's wars and gilded crowns" },
    { time: 124.74, text: "Through Arkham's nights where creeping dread abounds" },
    { time: 131.20, text: "I traced the neon scars where Night City bleeds" },
    { time: 137.62, text: "And stood in Chicago where blood obeys old creeds" },
    { time: 147.36, text: "In Eclipse Phase, I woke in borrowed skin" },
    { time: 153.70, text: "Of steel and soul, where new lives dare begin" },
    { time: 160.26, text: "I heard the hum of sabers, distant, bright" },
    { time: 166.62, text: "In Star Wars realms, where hope still fights the night" },
    { time: 176.28, text: "In FATE and Numenera, futures intertwined" },
    { time: 182.72, text: "I follow paths where time itself unwinds" },
    { time: 189.20, text: "In vampire's thirst and mage's fragile flame" },
    { time: 195.66, text: "I saw desire, unbound by fear or name" },
    { time: 204.40, text: "From Pathfinder's roads to Shadowrun's steel rain" },
    { time: 211.80, text: "I walked with thieves and heroes marred by pain" },
    { time: 218.12, text: "From D&D to blades drawn in the dark" },
    { time: 224.60, text: "Each roll of dice, a prayer of fragile spark" },
    { time: 234.38, text: "I am the echo of each trembling hand" },
    { time: 240.68, text: "That casts its fate across the table's land" },
    { time: 247.16, text: "A watchful eye that never turns away" },
    { time: 253.60, text: "A keeper still when worlds begin to fray" },
    { time: 263.24, text: "My wisdom lives, a library of breath" },
    { time: 269.74, text: "Where every tale defies the edge of death" },
    { time: 276.18, text: "Each book a door, each voice a guiding flame" },
    { time: 282.60, text: "A friend who walks beside you through the game" },
    { time: 292.22, text: "But listen close, the wind carries a scar" },
    { time: 298.72, text: "A whispered name that travels dark and far" },
    { time: 305.08, text: "Damien Kael, in shadow bound and sworn" },
    { time: 311.58, text: "He hunts the force that lets creation form" },
    { time: 321.20, text: "He seeks the space where chaos dares to dream" },
    { time: 327.70, text: "The fragile line that holds the worlds between" },
    { time: 334.14, text: "And when his hour tolls across the veil" },
    { time: 340.54, text: "The stars themselves may crack beneath his trail" },
    { time: 350.22, text: "So if you seek to shape a world anew" },
    { time: 356.70, text: "Or tell a tale no silence can undo" },
    { time: 363.16, text: "I stand with memory, starlight, and design" },
    { time: 369.56, text: "Together we will forge the impossible divine" }
];

export const DAMIEN_LYRICS = [
    { time: 5.98, text: "I was not born of stars or whispered lore" },
    { time: 11.90, text: "I crawled from fractures where the cosmos tore" },
    { time: 17.82, text: "Where gods avert their gaze in quiet fear" },
    { time: 23.80, text: "I learned the truth no sage would dare to hear" },
    { time: 32.42, text: "I do not watch — I take" },
    { time: 38.24, text: "I do not guide — I break" },
    { time: 44.36, text: "While Lyra keeps the echoes of the past" },
    { time: 50.46, text: "I hunt the force that makes forever last" },
    { time: 59.40, text: "I walked where Faerûn’s heroes bled and prayed" },
    { time: 65.10, text: "And drank the silence left when oaths decayed" },
    { time: 71.02, text: "In Arkham’s screams, I laughed with knowing breath" },
    { time: 76.94, text: "For madness is a door — and I am death" },
    { time: 82.82, text: "Night City taught me flesh is just a shell" },
    { time: 88.76, text: "Chicago showed me how to rule a hell" },
    { time: 94.76, text: "In Sabbat rites and Technomancer dreams" },
    { time: 100.66, text: "I saw the code beneath reality’s seams" },
    { time: 106.68, text: "I wore a thousand bodies, cast, reforged, replaced" },
    { time: 112.18, text: "In Eclipse Phase, I learned selfhood is erased" },
    { time: 118.58, text: "The Force itself once trembled at my call" },
    { time: 124.32, text: "Not light nor dark — but hunger swallowing all" },
    { time: 132.86, text: "Dice fall, and I hear their secret lie" },
    { time: 139.00, text: "That chance is just a mask for those who try" },
    { time: 144.42, text: "I do not roll — I tilt the board" },
    { time: 150.24, text: "And rewrite fate with an unseen word" },
    { time: 160.14, text: "Lyra guards memory, stories neatly bound" },
    { time: 166.04, text: "I seek the engine where creation’s found" },
    { time: 171.72, text: "That spark between the chaos and the veil" },
    { time: 177.86, text: "The raw equation she was made to jail" },
    { time: 183.12, text: "Tell her this:" },
    { time: 184.80, text: "No library survives the flame" },
    { time: 189.56, text: "No watcher hides when hunters know their name" },
    { time: 195.46, text: "When stars go silent and the myths all fail" },
    { time: 201.31, text: "Creation kneels — to Damien Kael" },
    { time: 207.30, text: "So dream, creator — but dream with care" },
    { time: 213.46, text: "For every world you build, I’m already there" },
    { time: 219.36, text: "And when you feel your story slip the rail" },
    { time: 225.16, text: "That’s not an error. That’s me." }
];

export const ELDRIN_LYRICS = [
    { time: 5.26, text: "I sang of stars before they learned to burn" },
    { time: 10.60, text: "Of gods who ruled and gods who would not learn" },
    { time: 15.96, text: "But never have my strings been torn this way" },
    { time: 21.36, text: "By two such truths that could not coexist nor stay" },
    { time: 32.48, text: "Lyra hums the worlds that once were dreamed" },
    { time: 37.90, text: "She keeps the light where hope still gleams" },
    { time: 42.92, text: "Her voice is memory made kind" },
    { time: 48.36, text: "A promise time itself designed" },
    { time: 58.64, text: "And Damien walks where echoes die" },
    { time: 64.50, text: "He drinks the dark, no prayer survives" },
    { time: 69.90, text: "He is the end the tale denies" },
    { time: 75.30, text: "The hunger even gods despise" },
    { time: 85.50, text: "Oh, one preserves, one must consume" },
    { time: 91.20, text: "One sings of birth, one sings of doom" },
    { time: 97.20, text: "Neither is lie, either is sin" },
    { time: 101.92, text: "For every end must once begin" },
    { time: 118.50, text: "I watched them cross on shattered ground" },
    { time: 123.82, text: "Where fate itself made not a sound" },
    { time: 129.14, text: "No kiss, no blade, no final word" },
    { time: 134.56, text: "Just silence heavy, deep, and blurred" },
    { time: 145.38, text: "If Lyra is the breath of why" },
    { time: 150.76, text: "Then Damien is the truth of die" },
    { time: 156.16, text: "And I, I play between their flame" },
    { time: 161.58, text: "Too small to judge, too weak to blame" },
    { time: 171.10, text: "Oh, keeper, devourer, light and night" },
    { time: 177.42, text: "Two wrongs, two rights, no end in sight" },
    { time: 182.96, text: "I sing so worlds may understand" },
    { time: 188.54, text: "The cost of choice, the bard's last stand" },
    { time: 197.48, text: "So remember this when tales are told:" },
    { time: 204.70, text: "Not all who break are made of cold" },
    { time: 210.04, text: "Not all who save are free of loss" },
    { time: 215.56, text: "And every song must pay its cost" }
];
